version: '3.8'
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    container_name: fafp_database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: fafp_database

volumes:
  database:
